config/routes.rb
Reddit::Application.routes.draw do
  resources :users
  resource :session
  resources :subs
  resources :links do
    post 'upvote'
    post 'downvote'
  end
  resources :comments
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :title, :url, :submitter, :sub_ids, :comment_ids

  validates :title, :url, :submitter, presence: true

  belongs_to(
    :submitter,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :links
  )

  has_many(
    :sub_links,
    class_name: 'SubLink',
    foreign_key: :link_id,
    primary_key: :id,
    inverse_of: :link
  )

  has_many(
    :comments,
    class_name: 'Comment',
    foreign_key: :link_id,
    primary_key: :id,
    inverse_of: :link
  )

  has_many(
    :votes,
    class_name: "UserVote",
    foreign_key: :link_id,
    primary_key: :id,
    inverse_of: :link
  )

  has_many :subs, through: :sub_links, source: :sub

  def comments_by_parent_id
    comment_hash = {}
    comments.each do |comment|
      comment_hash[comment.parent_comment_id] ||= []
      comment_hash[comment.parent_comment_id] += [comment]
    end

    comment_hash
  end

  def popularity
    votes.sum(:vote_type)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :require_current_user, only: [:new, :create, :edit, :destroy, :update, :upvote, :downvote]
  before_filter :current_link, only: [:show, :edit, :update, :destroy]
  before_filter :is_submitter, only: [:edit, :destroy, :update]

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.new(params[:link])
    unless params[:comment][:body].blank?
      comment = @link.comments.new(params[:comment])
      comment.author = current_user
    end
    if @link.save
      redirect_to @link
    else
      flash[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def show
    @comments = @link.comments_by_parent_id
  end

  def update
    to_delete = @link.comment_ids - params[:link][:comment_ids]
    Comment.where(id: to_delete).destroy_all
    if @link.update_attributes(params[:link])
      redirect_to @link
    else
      flash[:errors] = @links.errors.full_messages
      render :edit
    end
  end

  def destroy
    @link.destroy
    redirect_to links_url
  end

  def upvote
    @link = Link.find(params[:link_id])
    vote = current_user.votes.new(vote_type: 1, link: @link)
    if vote.save
      redirect_to :back
    else
      flash[:errors] = ['You already voted on this link']
      redirect_to :back
    end
  end

  def downvote
    @link = Link.find(params[:link_id])
    vote = current_user.votes.new(vote_type: -1, link: @link)
    if vote.save
      redirect_to :back
    else
      flash[:errors] = ['You already voted on this link']
      redirect_to :back
    end
  end

  private
  def current_link
    @link ||= Link.find(params[:id])
  end

  def is_submitter
    redirect_to @link unless @link.submitter.id == current_user.id
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_link.html.erb
<%= %>
<%= @link.title %>
<br>
<%= @link.url %>
<br>
<%= @link.description %>
<br>
<%= @link.submitter.username %>
<br>
<% if current_user == @link.submitter %>
  <%= link_to "Edit", edit_link_url(@link) %>
<% end %>

Comments
<form action="/comments" method="POST">
  <label for="add_comment">Add Comment</label><input type="text" name="comment[body]" value="" id="add_comment">
  <input type="hidden" name="comment[link_id]" value="<%= @link.id %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Add Comment" id="">
</form>
<%= render @comments[nil] unless @comments[nil].nil? %>

app/views/links/edit.html.erb
Edit Link
<form action="<%= link_url(@link) %>" method="POST">
  <label for="link_title">Title</label><input type="text" name="link[title]" value="<%= @link.title %>" id="link_title">
  <label for="link_url"></label><input type="text" name="link[url]" value="<%= @link.url %>" id="link_url">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <label for="link_description"></label><textarea name="link[description]" id="link_description"><%= @link.description %></textarea>
  <% Sub.all.each do |sub| %>
    <label for="link_sub_<%= sub.id %>"></label><input type="checkbox" name="link[sub_ids][]" value="<%= sub.id %>" id="link_sub_<%= sub.id %>" <%= "checked".html_safe if @link.sub_ids.include?(sub.id) %>>
    <br>
  <% end %>
  <label>Comments to Show</label>
  <% top_level_comments = @link.comments_by_parent_id[nil] || [] %>
  <% top_level_comments.each do |comment| %>
  <label>
    <%= comment.body %>
    <input type="checkbox" name="link[comment_ids][]" value='<%= comment.id %>'
      <%= "checked".html_safe if @link.comment_ids.include?(comment.id)%>>
  </label>
  <% end %>
  <input type="hidden" name="link[comment_ids][]" value="">
  <input type="submit" value="Update Link">
</form>

app/views/links/new.html.erb
Submit Link
<form action="/links" method="POST">
  <label for="link_title">Title</label><input type="text" name="link[title]" value="<%= @link.title %>" id="link_title">
  <label for="link_url">URL</label><input type="text" name="link[url]" value="<%= @link.url %>" id="link_url">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="link_description">Description</label><textarea name="link[description]" id="link_description"><%= @link.description %></textarea>
  <% Sub.all.each do |sub| %>
    <label for="link_sub_<%= sub.id %>"><%= sub.name %></label><input type="checkbox" name="link[sub_ids][]" value="<%= sub.id %>" id="link_sub_<%= sub.id %>" <%= "checked".html_safe if @link.sub_ids.include?(sub.id) %>>
    <br>
  <% end %>
  <label for="add_comment">Add Comment</label><input type="text" name="comment[body]" value="" id="add_comment">
  <input type="submit" value="Submit Link">
</form>

app/views/links/show.html.erb
<%= render @link %>