config/routes.rb
Reddit::Application.routes.draw do
  resources :users
  resource :session
  resources :subs
  resources :links do
    post 'upvote'
    post 'downvote'
  end
  resources :comments
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :name, :moderator

  validates :name, :moderator, presence: true
  validates :name, uniqueness: true

  belongs_to(
    :moderator,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :subs
  )

  has_many(
    :sub_links,
    class_name: 'SubLink',
    foreign_key: :sub_id,
    primary_key: :id,
    inverse_of: :sub
  )

  has_many :links, through: :sub_links, source: :link
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :require_current_user, except: [:index, :show]

  def index
    @links = Kaminari.paginate_array(Link.all.sort_by(&:popularity).reverse).page(params[:page]).per(25)

    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    @links = Kaminari.paginate_array(@sub.links.sort_by(&:popularity).reverse).page(params[:page]).per(25)
    render :show
  end

  def new
    render :new
  end

  def create
    @sub = current_user.subs.new(params[:sub])
    if @sub.save
      redirect_to @sub
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if current_user.id == @sub.moderator.id
      if @sub.update_attributes(params[:sub])
        redirect_to @sub
      else
        flash[:errors] = @sub.errors.full_messages
        render :edit
      end
    else
      flash[:errors] = "You can only edit this sub if you're the moderator"
      redirect_to @sub
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
Edit Sub
<form action="<%= sub_url(@sub) %>" method="post">
  <label for="sub_name">Name</label>
  <input type="text" id="sub_name" name="sub[name]" value="<%= @sub.name %>">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <br>
  <input type="submit" value="Update Sub">
</form>

app/views/subs/index.html.erb
<ul>
  <% @links.each do |link| %>
    <li>
      <%= link.popularity %>
      <%= button_to "Upvote", link_upvote_url(link) %>
      <%= button_to "Downvote", link_downvote_url(link) %>
      <%= link_to link.title, link_url(link) %>
    </li>
  <% end %>
</ul>
<%= paginate @links %>

app/views/subs/new.html.erb
Create Sub
<form action="/subs" method="post">
  <label for="sub_name">Name</label>
  <input type="text" id="sub_name" name="sub[name]">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <br>
  <input type="submit" value="Create new Sub">
</form>

app/views/subs/show.html.erb
<%= @sub.name %>
<ul>
  <% @links.each do |link| %>
    <li>
      <%= link.popularity %>
      <%= button_to "Upvote", link_upvote_url(link) %>
      <%= button_to "Downvote", link_downvote_url(link) %>
      <%= link_to link.title, link_url(link) %>
    </li>
  <% end %>
</ul>
<%= paginate @links %>